[build]
  command = "yarn rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  # To use [Netlify Dev](https://www.netlify.com/products/dev/),
  # install netlify-cli from https://docs.netlify.com/cli/get-started/#installation
  # and then use netlify link https://docs.netlify.com/cli/get-started/#link-and-unlink-sites
  # to connect your local project to a site already on Netlify
  # then run netlify dev and our app will be accessible on the port specified below
  framework = "redwoodjs"
  # Set targetPort to the [web] side port as defined in redwood.toml
  targetPort = 8910
  # Point your browser to this port to access your RedwoodJS app
  port = 8888

[[redirects]]
  from = "/docs/*"
  to = "https://docs.redwoodjs.com/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cookbook"
  to = "https://docs.redwoodjs.com/docs/how-to/index"
  status = 301
  force = true

[[redirects]]
  from = "/cookbook/*"
  to = "https://docs.redwoodjs.com/docs/how-to/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial"
  to = "https://docs.redwoodjs.com/docs/tutorial/welcome-to-redwood"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/*"
  to = "https://docs.redwoodjs.com/docs/tutorial/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contributing"
  to = "https://docs.redwoodjs.com/docs/contributing"

[[redirects]]
  from = "/reference/command-line-interface"
  to = "https://docs.redwoodjs.com/docs/cli-commands"
  status = 301
  force = true

[[redirects]]
  from = "/quick-start"
  to = "https://docs.redwoodjs.com/docs/quick-start"
  status = 301
  force = true

[[redirects]]
  from = "/quickstart"
  to = "https://docs.redwoodjs.com/docs/quick-start"
  status = 301
  force = true

[[redirects]]
  from = "/newsletter"
  to = "https://mailchi.mp/redwoodjs/redwoodjs-newsletter"
  force = true

[[redirects]]
  from ="/community"
  to ="https://community.redwoodjs.com/t/welcome-to-the-redwoodjs-community/2416"

[[redirects]]
  from ="/events"
  to ="https://community.redwoodjs.com/t/redwood-events-you-re-invited/3853"

[[redirects]]
  from ="/startup-club"
  to ="https://forms.gle/fYsacoY4uKQmP24o8"

[[redirects]]
  from = "/good-first-issue"
  to = "https://github.com/orgs/redwoodjs/projects/11"

[[redirects]]
  from = "/roadmap"
  to = "/#roadmap"
  status = 301
  force = true

[[redirects]]
  from = "/jobs"
  to = "https://community.redwoodjs.com/c/jobs/29"
  status = 301
  force = true

[[redirects]]
  from = "/blog/bighorn-walkthrough"
  to = "/blog/rsc-now-in-redwoodjs"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
